default['selfsigned_certificate']['destination'] = "/usr/var/ssl/certs/"
default['selfsigned_certificate']['passphrase'] = "devopsdemo"
default['selfsigned_certificate']['country'] = "USA"
default['selfsigned_certificate']['state'] = "NJ"
default['selfsigned_certificate']['city'] = "Piscataway"
default['selfsigned_certificate']['org'] = "Devops"
default['selfsigned_certificate']['depart'] = "demo"
default['selfsigned_certificate']['email'] = "Devops@demo.com"
default['ssl_cert']['source'] = '/usr/var/ssl/certs/server.crt'
default['ssl_key']['source'] = '/usr/var/ssl/certs/server.key'
default['ssl_host']['ip']='52.37.134.198'
